<?php

namespace M2Boilerplate\CriticalCss\Plugin;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

class AsyncCssPlugin extends \Magento\Theme\Controller\Result\AsyncCssPlugin
{

    private const XML_PATH_USE_CSS_CRITICAL_PATH = 'dev/css/use_css_critical_path';

    private const CRITICAL_CSS_GENERATE_QUERY_PARAM = 'critical_css_generate';
    /**
     * @var ScopeConfigInterface
     */
    private $scopeConfig;

    /**
     * @var \Magento\Framework\App\RequestInterface
     */
    private $request;
    /**
     * @param ScopeConfigInterface $scopeConfig
     */
    public function __construct(
        ScopeConfigInterface $scopeConfig,
        \Magento\Framework\App\RequestInterface $request
    )
    {
        $this->scopeConfig = $scopeConfig;
        $this->request = $request;
    }
    /**
     * Returns information whether css critical path is enabled
     * css critical is disabled for requests generated by critical npm headless browser
     * @return bool
     */
    private function isCssCriticalEnabled(): bool
    {
        return $this->isCriticalCssGenerateRequest() === false
            && $this->scopeConfig->isSetFlag(
            self::XML_PATH_USE_CSS_CRITICAL_PATH,
            ScopeInterface::SCOPE_STORE
        );
    }

    /**
     * indicates whether request is generated by critical npm headless browser as part of critical css generation process
     * @return mixed
     */
    private function isCriticalCssGenerateRequest() {
        return $this->request->getParam(self::CRITICAL_CSS_GENERATE_QUERY_PARAM, false);
    }
}
